### ISSUE TITLE
Don't get it... uses jest or not?

### ISSUE THREAD

**Issue by mdelgadov** [PetrNikolas/marley#1]
Excuse my pickiness but don't understand, it says it uses jest... or when will it?

**Comment by PetrNikolas** [comment]
Sorry for late comment. You can check a new version of Marley now.

**Comment by mdelgadov** [comment]
atta boy! I like your Marley... i think it's a good plan for what is a good basic set of features in a pwa

**Comment by PetrNikolas** [comment]
Yeah, thanks. You can contributte, if you can
